(function defineCockpitMockSignals() {
  "use strict";

  window.COCKPIT_MOCK_SIGNALS = [
    {
      signalId: "demo-fin-001",
      signalType: "financial_pressure_signal",
      title: "فشار مالی",
      summary: "نسبت خروجی نقدی ساختگی از محدوده نمایشی عبور کرده است.",
      primaryMetric: "۷۸٪",
      secondaryMetric: "روند نمایشی: افزایشی",
      riskLevel: "high",
      confidenceLevel: "high",
      sourceModule: "FIN-DEMO",
      sourceStatus: "synthetic_ready",
      suggestedAction: "بررسی مفهومی تعهدهای نزدیک و جریان ورودی",
      requiresManagerDecision: true,
      auditState: "audit_available",
      drillDownTargetConcept: "Financial Pressure Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-product-002",
      signalType: "product_import_warning_signal",
      title: "هشدار ورود کالا",
      summary: "سه رکورد نمونه به علت تعارض بارکد در حالت توقف نمایشی هستند.",
      primaryMetric: "۳ مورد",
      secondaryMetric: "از ۲۴ رکورد ساختگی",
      riskLevel: "conflict",
      confidenceLevel: "high",
      sourceModule: "PRODUCT-DEMO",
      sourceStatus: "synthetic_blocked",
      suggestedAction: "مشاهده مفهومی تعارض‌ها و ارجاع به review",
      requiresManagerDecision: true,
      auditState: "audit_required",
      drillDownTargetConcept: "Product Import Review Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-review-003",
      signalType: "manager_review_queue_signal",
      title: "صف تصمیم مدیر",
      summary: "چند تصمیم نمونه با اولویت‌های متفاوت منتظر بررسی مفهومی هستند.",
      primaryMetric: "۹ تصمیم",
      secondaryMetric: "۲ مورد با اولویت بالا",
      riskLevel: "medium",
      confidenceLevel: "high",
      sourceModule: "CONTROL-DEMO",
      sourceStatus: "synthetic_ready",
      suggestedAction: "مرتب‌سازی مفهومی بر اساس ریسک و زمان انتظار",
      requiresManagerDecision: true,
      auditState: "audit_available",
      drillDownTargetConcept: "Manager Review Queue Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-inventory-004",
      signalType: "inventory_shortage_signal",
      title: "کمبود موجودی",
      summary: "دو قلم نمونه به سطح هشدار مصنوعی نزدیک شده‌اند.",
      primaryMetric: "۲ قلم",
      secondaryMetric: "پوشش نمایشی: ۴ روز",
      riskLevel: "medium",
      confidenceLevel: "medium",
      sourceModule: "INV-DEMO",
      sourceStatus: "synthetic_partial",
      suggestedAction: "بازبینی مفهومی موجودی و نیاز خرید",
      requiresManagerDecision: false,
      auditState: "audit_available",
      drillDownTargetConcept: "Inventory Shortage Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-production-005",
      signalType: "production_risk_signal",
      title: "ریسک تولید",
      summary: "یک فرمول نمونه به دلیل ورودی ناقص نیازمند بررسی انسانی است.",
      primaryMetric: "۱ فرمول",
      secondaryMetric: "اثر ساختگی: متوسط",
      riskLevel: "manual_only",
      confidenceLevel: "medium",
      sourceModule: "PROD-DEMO",
      sourceStatus: "synthetic_review",
      suggestedAction: "بررسی مفهومی مواد و مفروضات فرمول",
      requiresManagerDecision: true,
      auditState: "audit_required",
      drillDownTargetConcept: "Production Risk Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-workforce-006",
      signalType: "workforce_risk_signal",
      title: "ریسک نیروی انسانی",
      summary: "یک تداخل برنامه ساختگی در بازه پرتراکم هفته دیده شده است.",
      primaryMetric: "۱ تداخل",
      secondaryMetric: "ریسک نمایشی: پایین",
      riskLevel: "low",
      confidenceLevel: "medium",
      sourceModule: "WF-DEMO",
      sourceStatus: "synthetic_ready",
      suggestedAction: "مشاهده مفهومی برنامه و پوشش فعالیت",
      requiresManagerDecision: false,
      auditState: "audit_available",
      drillDownTargetConcept: "Workforce Risk Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-ai-007",
      signalType: "ai_suggestion_signal",
      title: "پیشنهاد هوشمند",
      summary: "پیشنهاد ساختگی: ابتدا تعارض ورود کالا بررسی شود، سپس صف تصمیم مرتب گردد.",
      primaryMetric: "۲ پیشنهاد",
      secondaryMetric: "فقط پیشنهاد، بدون اقدام",
      riskLevel: "low",
      confidenceLevel: "medium",
      sourceModule: "AI-DEMO",
      sourceStatus: "synthetic_suggestion",
      suggestedAction: "مشاهده دلیل و شواهد ساختگی پیشنهاد",
      requiresManagerDecision: true,
      auditState: "audit_available",
      drillDownTargetConcept: "AI Suggestion Review Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    },
    {
      signalId: "demo-crisis-008",
      signalType: "crisis_signal",
      title: "سیگنال بحران",
      summary: "ترکیب ساختگی فشار مالی و تعارض کالا نیازمند توجه فوری است.",
      primaryMetric: "سطح ۲",
      secondaryMetric: "۲ ماژول درگیر",
      riskLevel: "high",
      confidenceLevel: "low",
      sourceModule: "COCKPIT-DEMO",
      sourceStatus: "synthetic_uncertain",
      suggestedAction: "جمع‌آوری شواهد بیشتر و ارجاع مفهومی به مدیر",
      requiresManagerDecision: true,
      auditState: "audit_missing",
      drillDownTargetConcept: "Crisis Signal Concept",
      generatedAt: "۲۰ خرداد ۱۴۰۵ - داده ساختگی"
    }
  ];
})();
