export interface WorkforceStorageKeyRegistryItem {
  key: string;
  title: string;
  domain: "core" | "analysis" | "operations" | "system" | "audit";
  ownerService: string;
  isCritical: boolean;
  includeInBackup: boolean;
  includeInSnapshot: boolean;
  includeInImport: boolean;
  description: string;
}

export const workforceStorageKeyRegistry = [
  {
    key: "komak.workforce.spaces.v1",
    title: "فضاها",
    domain: "core",
    ownerService: "workforceService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "داده پایه فضاهای کاری و ظرفیت آنها.",
  },
  {
    key: "komak.workforce.employees.v1",
    title: "کارمندان",
    domain: "core",
    ownerService: "workforceService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "داده پایه کارمندان، نقش‌ها و مهارت‌ها.",
  },
  {
    key: "komak.workforce.taskTypes.v1",
    title: "نوع کارها",
    domain: "core",
    ownerService: "workforceService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "تعریف نوع کارها و نیازهای تمرکز/فضا.",
  },
  {
    key: "komak.workforce.scheduleItems.v1",
    title: "برنامه هفتگی",
    domain: "core",
    ownerService: "workforceService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "آیتم‌های برنامه هفتگی که analyzer از آنها تغذیه می‌شود.",
  },
  {
    key: "komak.workforce.rules.v1",
    title: "قوانین تحلیل",
    domain: "analysis",
    ownerService: "workforceService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "قوانین فعال/غیرفعال تحلیل هفتگی.",
  },
  {
    key: "komak.workforce.analysisSettings.v1",
    title: "تنظیمات تحلیل",
    domain: "analysis",
    ownerService: "analysisSettingsService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "آستانه‌ها و ساعت‌های کاری تحلیل.",
  },
  {
    key: "komak.workforce.compatibilityRules.v1",
    title: "قوانین سازگاری",
    domain: "analysis",
    ownerService: "compatibilityService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "سازگاری نوع کار با فضاها.",
  },
  {
    key: "komak.workforce.decisionQueue.v1",
    title: "صف تصمیم",
    domain: "operations",
    ownerService: "WorkforcePages decision queue storage",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "صف سناریوهای تصمیم‌گیری مدیر.",
  },
  {
    key: "komak.workforce.decisionReports.v1",
    title: "گزارش‌های تصمیم",
    domain: "operations",
    ownerService: "decisionReportService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "گزارش‌های تصمیم، آرشیو و مقایسه هفته‌ها.",
  },
  {
    key: "komak.workforce.monthlyGoals.v1",
    title: "هدف‌های ماهانه",
    domain: "operations",
    ownerService: "monthlyGoalService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "هدف‌های مدیریتی و وضعیت سلامت ماهانه.",
  },
  {
    key: "komak.workforce.preventiveAlertStates.v1",
    title: "وضعیت هشدارهای پیشگیرانه",
    domain: "operations",
    ownerService: "preventiveAlertStateService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "acknowledge/resolve/dismiss هشدارهای پیشگیرانه.",
  },
  {
    key: "komak.workforce.snapshots.v1",
    title: "Snapshotها",
    domain: "audit",
    ownerService: "workforceBackupService",
    isCritical: false,
    includeInBackup: false,
    includeInSnapshot: false,
    includeInImport: false,
    description: "Container داخلی snapshotهاست و عمدا از bundle مستقیم خارج است تا snapshot داخل snapshot بازگشتی ساخته نشود.",
  },
  {
    key: "komak.workforce.maintenanceReports.v1",
    title: "گزارش‌های نگهداری",
    domain: "system",
    ownerService: "workforceMaintenanceService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "گزارش‌های سلامت localStorage و توصیه‌های نگهداری.",
  },
  {
    key: "komak.workforce.launchChecklist.v1",
    title: "چک‌لیست راه‌اندازی",
    domain: "system",
    ownerService: "launchChecklistService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "وضعیت آیتم‌های چک‌لیست راه‌اندازی.",
  },
  {
    key: "komak.workforce.launchSignoffs.v1",
    title: "تأییدهای راه‌اندازی",
    domain: "audit",
    ownerService: "launchSignoffService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "baselineهای امضاشده راه‌اندازی و checksumهای مرجع.",
  },
  {
    key: "komak.workforce.operationalResignoffs.v1",
    title: "بازتأییدهای عملیاتی",
    domain: "audit",
    ownerService: "operationalResignoffService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "بازتأیید baseline پس از drift و تغییرات مهم.",
  },
  {
    key: "komak.workforce.operationalHistory.v1",
    title: "تاریخچه عملیاتی",
    domain: "audit",
    ownerService: "operationalHistoryService",
    isCritical: true,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "رویدادهای audit شامل backup، drift، signoff و import.",
  },
  {
    key: "komak.workforce.historyRetentionPolicy.v1",
    title: "سیاست نگهداری تاریخچه",
    domain: "audit",
    ownerService: "historyRetentionService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "تنظیمات retention، archive و انقضای بازتأیید.",
  },
  {
    key: "komak.workforce.historyArchives.v1",
    title: "آرشیو تاریخچه",
    domain: "audit",
    ownerService: "historyRetentionService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "آرشیو رویدادهای قدیمی تاریخچه عملیاتی.",
  },
  {
    key: "komak.workforce.operationsCalendar.v1",
    title: "تقویم کنترل‌ها",
    domain: "system",
    ownerService: "operationsCalendarService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "کنترل‌های دوره‌ای، snooze، complete و status آنها.",
  },
  {
    key: "komak.workforce.operationsControlSchedulePolicy.v1",
    title: "سیاست زمان‌بندی کنترل‌ها",
    domain: "system",
    ownerService: "operationsControlSettingsService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "cadence و اولویت کنترل‌های عملیاتی.",
  },
  {
    key: "komak.workforce.operationsControlExportOptions.v1",
    title: "تنظیمات خروجی کنترل‌ها",
    domain: "system",
    ownerService: "operationsControlSettingsService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "گزینه‌های export تقویم کنترل‌ها.",
  },
  {
    key: "komak.workforce.operationalNotificationPreferences.v1",
    title: "تنظیمات اعلان عملیاتی",
    domain: "system",
    ownerService: "operationsControlSettingsService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "ترجیحات اعلان local/in-app کنترل‌ها.",
  },
  {
    key: "komak.workforce.operationalInAppNotifications.v1",
    title: "اعلان‌های داخل برنامه",
    domain: "system",
    ownerService: "operationalNotificationService",
    isCritical: false,
    includeInBackup: true,
    includeInSnapshot: true,
    includeInImport: true,
    description: "اعلان‌های in-app ساخته‌شده از کنترل‌های عملیاتی.",
  },
] as const satisfies readonly WorkforceStorageKeyRegistryItem[];

export const workforceKnownStorageKeys = workforceStorageKeyRegistry.map((item) => item.key);
export const workforceBackupStorageKeys = workforceStorageKeyRegistry.filter((item) => item.includeInBackup).map((item) => item.key);
export const workforceSnapshotDataKeys = workforceStorageKeyRegistry.filter((item) => item.includeInSnapshot).map((item) => item.key);
export const workforceImportStorageKeys = workforceStorageKeyRegistry.filter((item) => item.includeInImport).map((item) => item.key);

export function findWorkforceStorageKey(key: string) {
  return workforceStorageKeyRegistry.find((item) => item.key === key);
}
